### ISSUE TITLE
Google Feedback on 4.4 Beta

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-DOM-lib-generator#1067]
Opening on the behalf of @h-joo from https://github.com/microsoft/TypeScript/issues/45047:

> ### Readonly attributes in DOMPoint, DOMMatrix, DOMRect
> 
> Some properties of DOMPoint, DOMMatrix, DOMRect became readonly, and this no
> longer match the specification. This is because these types no longer override
> properties from the extended types to be read/write.
> 
> Compare(DOMPoint):
> 
> *   https://github.com/microsoft/TypeScript/blob/release-4.3/lib/lib.dom.d.ts#L3979
> *   https://github.com/microsoft/TypeScript/blob/release-4.4/lib/lib.dom.d.ts#L3886
> 
> Compare(DOMMatrix):
> 
> *   https://github.com/microsoft/TypeScript/blob/release-4.3/lib/lib.dom.d.ts#L3854
> *   https://github.com/microsoft/TypeScript/blob/release-4.4/lib/lib.dom.d.ts#L3783
> 
> Compare(DOMRect):
> 
> *   https://github.com/microsoft/TypeScript/blob/release-4.3/lib/lib.dom.d.ts#L4026
> *   https://github.com/microsoft/TypeScript/blob/release-4.4/lib/lib.dom.d.ts#L3929
> 
> ### Removed Types
> 
> SpeechRecognition, RTCError got removed from lib.dom.d.ts. There are existing
> code which use this API, and it would be difficult to migrate without proper
> type support either from the compiler or from definitelyTyped.
> 
> *   https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognitionEvent
> *   https://developer.mozilla.org/en-US/docs/Web/API/RTCError
> 
> ### Offscreen Rendering API changes
> 
> OffscreenCanvas still exists, but it's marked as deprecated. Though it is no
> longer a value, i.e. code calling `new OffscreenCanvas` no longer works, it's
> just an interface. We think this might be unintentional. Though, we would still
> be able to migrate via referring to the types defined in
> [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).
> 
> *   https://github.com/microsoft/TypeScript/blob/release-4.3/lib/lib.dom.d.ts#L11087
> *   https://github.com/microsoft/TypeScript/blob/release-4.4/lib/lib.dom.d.ts#L10832
> 
> ### ShadowRoot interface changes
> 
> ShadowRoot is a subtype of DocumentFragment. DocumentFragment has a
> getElementById which returns HTMLElement. In 4.4-beta, DocumentFragment no
> longer defines its own getElementById method, meaning
> HTMLElement.prototype.shadowRoot.getElementById returns Element, not
> HTMLElement. This causes hundreds of breakages of code using shadowRoot.
> 
> *   https://github.com/microsoft/TypeScript/blob/release-4.3/lib/lib.dom.d.ts#L4985
> *   https://github.com/microsoft/TypeScript/blob/release-4.4/lib/lib.dom.d.ts#L4717
> 
> ### ChildNode interface changes
> 
> In 4.4, ChildNode no longer extends Node. This seems like a bug.
> 
> *   https://github.com/microsoft/TypeScript/blob/release-4.3/lib/lib.dom.d.ts#L3531
> *   https://github.com/microsoft/TypeScript/blob/release-4.4/lib/lib.dom.d.ts#L3487
> 
> ### DocumentOrShadowRoot interface changes
> 
> DocumentOrShadowRoot no longer has getSelection, elementFromPoint,
> elementsFromPoint, caretFromRange. We also couldn't find in the repo whether
> this was intentional or not.
> 
> *   https://github.com/microsoft/TypeScript/blob/release-4.3/lib/lib.dom.d.ts#L4995
> *   https://github.com/microsoft/TypeScript/blob/release-4.4/lib/lib.dom.d.ts#L4725

**Comment by h-joo** [comment]
Thank you 😊

In the meanwhile we've found two more types which we missed to added to `Removed Types` section, which are VRDisplay and MediaStreamError.

**Comment by saschanaz** [comment]
>Readonly attributes in DOMPoint, DOMMatrix, DOMRect

It's my fault 😬, will fix it.

>Removed Types
>Offscreen Rendering API changes
>DocumentOrShadowRoot interface changes

Those are Chrome-only things, while `SpeechRecognition` is supported by Chrome and Safari but only with `webkit` prefix.

`OffscreenCanvas` seems like a good candidate for additional type package as suggested in https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1023, but for now I guess it should be added to DefinitelyTyped?

`SpeechRecognition` miiiight be added back, but I would also prefer DefinitelyTyped for this. 🤔

>ShadowRoot interface changes

The current type is "correct", but since `Document.getElementById` is already customized for easier use, I'll do the same there.

>ChildNode interface changes

It's a mixin interface implemented by some Node interfaces. The correct way to receive Nodes that can be children is `ChildNode & Node`, just like `ParentNode & Node` for Nodes that can be parents.

**Comment by h-joo** [comment]
Thank you @saschanaz and @DanielRosenwasser for the help. We've checked TS4.4-rc and I've seen much reduced breakages, and most of the remaining breakages it seems that we can fix it via DefinitelyTyped, or the use should be removed as it's vendor specific or deprecated. 

Though we still see some failures with respect to removed types which are things below : 

- SpeechRecognitionEvent
- RTCError, RTCErrorEvent 

as @saschanaz mentioned that `SpeechRecognitionEvent` might be added to DT, I was wondering if there are any plans, I guess I can also try adding that myself. 

For the RTCError, I am uncertain if it was intentional, but from [this commit](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54087/files) it seems the use of RTCErrorEvent seems to be commented out intentionally?

**Comment by saschanaz** [comment]
> as @saschanaz mentioned that `SpeechRecognitionEvent` might be added to DT, I was wondering if there are any plans, I guess I can also try adding that myself.

No immediate plan, you are free to do that.

> For the RTCError, I am uncertain if it was intentional, but from [this commit](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54087/files) it seems the use of RTCErrorEvent seems to be commented out intentionally?

[RTCError](https://developer.mozilla.org/en-US/docs/Web/API/RTCError#browser_compatibility) and [RTCErrorEvent](https://developer.mozilla.org/en-US/docs/Web/API/RTCErrorEvent#browser_compatibility) are excluded as they are also currently Chrome only. Maybe @types/webrtc should include them instead?

**Comment by h-joo** [comment]
Great, now all makes sense. Thank you for your help!!

**Comment by Haprog** [comment]
> There are no specs from W3C which declare that DocumentOrShadowRoot should have those properties (that I've found), only Document has them (which you can see in the dom.d.ts today)

This used to be declared in the Shadow DOM spec, but there's apparently some ongoing(?) work related to migrating that spec to other specs. See my related comment here: https://github.com/WICG/webcomponents/issues/661#issuecomment-992242293

It's weird to me that those are not _anymore_ shown in any live spec to be part of DocumentOrShadowRoot, but to me that looks like an accident also. I'm pretty sure they were not intentionally being dropped from specs.
