### ISSUE TITLE
Daily releases are happening without actual changes

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#1109]
0.0.18 and 0.0.19 are totally redundant when the repo had no commit. @orta

**Comment by orta** [comment]
Agree

**Comment by orta** [comment]
This is due to the difference in what is in a baseline (and thus available locally via the tag) and what we actually deploy to npm to `@types` via the build processing:

![Screen Shot 2021-08-24 at 4 22 47 PM](https://user-images.githubusercontent.com/49038/130644339-6d9c64e9-43d2-4de3-ad7d-68f387901325.png)

I'll switch it back to asking unpkg and that should be making proper comparisons

**Comment by saschanaz** [comment]
Or compare before the manipulation? Either way okay, though.
