### ISSUE TITLE
`navigator.clipboard` is typed as always being defined, but is `undefined` in non-secure contexts

### ISSUE THREAD

**Issue by alexburner** [microsoft/TypeScript-DOM-lib-generator#1150]
# lib Update Request

## Configuration Check

My compilation _target_ is `ESNext` and my _lib_ is `lib.dom.ts`.

## Missing / Incorrect Definition

`navigator.clipboard` is typed as always being defined, but it is `undefined` in non-secure contexts (such as HTTP)

```ts
interface Navigator extends NavigatorAutomationInformation, NavigatorConcurrentHardware, NavigatorContentUtils, NavigatorCookies, NavigatorID, NavigatorLanguage, NavigatorNetworkInformation, NavigatorOnLine, NavigatorPlugins, NavigatorStorage {
    readonly clipboard: Clipboard; // ← Should be `readonly clipboard?: Clipboard;`
    readonly credentials: CredentialsContainer;
    readonly doNotTrack: string | null;
    readonly geolocation: Geolocation;
    readonly maxTouchPoints: number;
    readonly mediaCapabilities: MediaCapabilities;
    readonly mediaDevices: MediaDevices;
    readonly mediaSession: MediaSession;
    readonly permissions: Permissions;
    readonly pointerEnabled: boolean;
    readonly serviceWorker: ServiceWorkerContainer;
    getGamepads(): (Gamepad | null)[];
    requestMediaKeySystemAccess(keySystem: string, supportedConfigurations: MediaKeySystemConfiguration[]): Promise<MediaKeySystemAccess>;
    sendBeacon(url: string | URL, data?: BodyInit | null): boolean;
    share(data?: ShareData): Promise<void>;
    vibrate(pattern: VibratePattern): boolean;
}
```

## Sample Code

```ts
navigator.clipboard.writeText('Hello!') // no TS error, but throws TypeError when served over HTTP
```

[Playground link](https://www.typescriptlang.org/play?target=99#code/HYQwbglg5iAuD2AnAdAYwDYQA4CN4kQBNkB3RCWAUwBVKAPWACgHIAJS9deAQmYEogA)

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#interfaces
https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure

**Comment by saschanaz** [comment]
I don't think we should make every SecureContext-only things as optional, when 1) non-secure HTTP is now considered as deprecated and 2) new features are mostly expected to be SecureContext-only.

That said, I think there can be something like `lib.dom.nonsecure.d.ts`. What do you think? @orta @sandersn

**Comment by saschanaz** [comment]
BTW I wonder we could add a tag system so that types can be toggled dynamically.

```ts
/**
 * @-ts-category SecureContext
 */
interface Foo {};
```

```
tsc --disable-categories SecureContext
```

**Comment by sandersn** [comment]
1. The seems niche enough that it could be an unofficial package. How many properties would need to change? Is it pretty much just `clipboard`?
2. Does SecureContext apply to the entire compilation?

**Comment by saschanaz** [comment]
Limiting a feature to SecureContext is generally recommended for new features and already applied for several features. Querying `SecureContext` in `./ed/idl` from a local clone of https://github.com/w3c/webref/ shows 268 matches.

In the above Navigator case, these members are SecureContext-only:

* `clipboard`
* `credentials`
* `mediaDevices`
* `serviceWorker`
* `requestMediaKeySystemAccess()`
* `share()`

**Comment by sandersn** [comment]
In the `Foo` example, is it possible that some parts of the compilation will be in SecureContext and able to access Foo, whereas other parts will not be in SecureContext, and not able to access Foo?

When I say 'niche', I think I might be misunderstanding the problem. My original reading was: 

1. uses outside SecureContext are now rare
2. uses outside SecureContext get the wrong type -- Clipboard instead of undefined
3. this is a small problem because (1) is rare and (2) is not horrible, and fairly common in the DOM elsewhere.

Is that accurate?

**Comment by saschanaz** [comment]
> In the `Foo` example, is it possible that some parts of the compilation will be in SecureContext and able to access Foo, whereas other parts will not be in SecureContext, and not able to access Foo?

I didn't think about such use in that example, since I thought users would 1) support both http/https or 2) https only. But maybe yes depending on project structure e.g. foo.tsconfig has `disableCategories` and bar.tsconfig does not? Admittedly not a well defined suggestion at this point, though.
 
> When I say 'niche', I think I might be misunderstanding the problem. My original reading was:
> 
> 1. uses outside SecureContext are now rare
> 
> 2. uses outside SecureContext get the wrong type -- Clipboard instead of undefined
> 
> 3. this is a small problem because (1) is rare and (2) is not horrible, and fairly common in the DOM elsewhere.
> 
> Is that accurate?

1. I have no data to call this rare. Being deprecated doesn't mean it's rare, since browsers are not actually forcing it *yet* and not every page automatically upgrades to HTTPS when accessed via HTTP. (Both [Firefox](https://support.mozilla.org/en-US/kb/https-only-prefs) and [Chrome](https://chromium-review.googlesource.com/c/chromium/src/+/2956486) have HTTPS-only mode now, so it eventually will be rare if it's not already.)
2. Exactly.
3. "Fairly common" because of differing browser supports, sure. This is not a support problem, I think we at least need a comment for affected features.

**Comment by saschanaz** [comment]
BTW, the tag system can be interesting as it can be something like

```ts
/**
 * @-ts-category SecureContext SupportedByFirefox SupportedBySafari SupportedByChrome
 */
interface Foo {};
```

And then users may be able to filter unsupported types on their own, rather than filing bugs for all the fancy types they need.

**Comment by orta** [comment]
I'm for assuming you're on https - but I like the idea of comments saying this is not valid in `http` 

I think the tagging is an interesting idea but could to be annoying at scale?

**Comment by saschanaz** [comment]
>but I like the idea of comments saying this is not valid in http

Seems like a lower fruit here!

>I think the tagging is an interesting idea but could to be annoying at scale?

TBH I'm not expert enough to say yes or no to this question, but I think letting the filter be a project-wide config can reduce the initial complexity?
