### ISSUE TITLE
Link to MDN docs

### ISSUE THREAD

**Issue by samestep** [microsoft/TypeScript-DOM-lib-generator#1464]
I was thinking it would be nice to be able to get a link to the MDN docs for a builtin JavaScript function while hovering over it in VS Code, so I started looking into the possibility of modifying this tool to emit docstrings like the following:

```typescript
/** [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clearRect) */
clearRect(x: number, y: number, w: number, h: number): void;
```

Would this be a welcome change? If so then I could work on the actual implementation and open a pull request, but I wanted to check first in case this wouldn't be wanted (since I don't see any links in docstrings currently).

**Comment by saschanaz** [comment]
Sounds good to me 👀. @sandersn, what do you think?

**Comment by sandersn** [comment]
This sounds like a good idea. Couple of thoughts:

1. I think we had some tool in the past that imported doc text from MDN, but eventually we deleted it. You might be able to look through git history and find some usable code.
2. Why delete it? I think it's because regular updates were too hard or not designed in. So, any new feature either needs to be created and checked-in once, or be easy to keep running regularly. Preferably automated on build, I think.

**Comment by saschanaz** [comment]
Implementation should be easy to implement and maintain, as BCD already provides us both spec links and MDN links.

Do we also want spec links there, btw?

**Comment by sandersn** [comment]
I think the spec is too hard to read for casual questions, personally.

**Comment by saschanaz** [comment]
Fair enough, MDN also provides spec links anyway!
