### ISSUE TITLE
Import missing types from BenjaminAster/TypeScript-types-for-new-JavaScript

### ISSUE THREAD

**Issue by kashav** [microsoft/TypeScript-DOM-lib-generator#1760]
There's a bunch of great definitions in @BenjaminAster's [TypeScript-types-for-new-JavaScript](https://github.com/BenjaminAster/TypeScript-types-for-new-JavaScript) repository. These should probably be imported into this repository.

I can work on this at some point in the future. Filing this for discussion.

**Comment by BenjaminAster** [comment]
Types that go into `lib.dom.d.ts` are, for the most part, automatically generated from the WebIDL of the specifications (This repository contains all the generator code plus some manual stuff). The policy for types to be included in `lib.dom.d.ts` is that the feature is supported in at least two browser engines (see [readme](https://github.com/microsoft/TypeScript-DOM-lib-generator?tab=readme-ov-file#why-is-my-fancy-api-still-not-available-here)). Most of the types in my [`new-javascript`](https://github.com/BenjaminAster/TypeScript-types-for-new-JavaScript) package are Chromium-only APIs, so they're not qualified to be included here and should probably live in my separate repository.

That said, *some* APIs that *are* supported in at least two engines are indeed missing from this repo and should be included here (and then excluded from `new-javascript`). Off the top of my head, these include:
- [`contentvisibilityautostatechange` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/contentvisibilityautostatechange_event) (the [`ContentVisibilityAutoStateChangeEvent`](https://developer.mozilla.org/en-US/docs/Web/API/ContentVisibilityAutoStateChangeEvent) is there, just not the `"contentvisibilityautostatechange"` event and `oncontentvisibilityautostatechange` event handler property themselves&mdash;which apparently is because the authors of [the spec](https://drafts.csswg.org/css-contain/#content-visibility-auto-state-change) [forgot](https://github.com/w3c/csswg-drafts/pull/7740) to put it in there :/
- [resizable ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/resize) (Although I assume that will get added in TypeScript 5.6, and it's probably out of scope for this repository)
- [`import.meta.resolve()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve) (probably overlooked by Microsoft devs since it's not specified in terms of WebIDL in the HTML spec. This should be added to [addedTypes.jsonc](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/inputfiles/addedTypes.jsonc) to the `ImportMeta` interface)

Also, working with service workers or shared workers in TypeScript by default is very inconvenient, as TypeScript's `lib.webworker.d.ts` doesn't include service-/shared worker specific stuff like the `"fetch"` event. My package [`better-typescript`](https://github.com/BenjaminAster/Better-TypeScript) (an extension of `new-javascript`) solves this by just putting all dedicated-/service-/shared worker specific stuff into the global definitions and you, the developer, then have to be smart enough to know which context the script runs in and should only use the APIs that are available there. Ideally, TypeScript would introduce a new concept such as "execution context" or whatever where you could specify on a per-file-basis in which context the code gets executed, but that is yet a different topic to explore.

**Comment by kashav** [comment]
Awesome, thanks for the comment, that makes sense. I'll stick to using new-javascript directly then.
