### ISSUE TITLE
Update Streams API to match the latest IDL

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#886]
https://github.com/whatwg/streams/pull/1035 did a massive work to introduce Web IDL, and that made our IDL outdated in complex way. Updating our code to use the upstream IDL will ease getting further update from this spec.

Pinging @MattiasBuelens who might be interested.

**Comment by MattiasBuelens** [comment]
Thanks for the ping. I'm indeed interested, I've even already started working on this in my fork, see [this `streams-webidl` branch](https://github.com/MattiasBuelens/TSJS-lib-generator/tree/streams-webidl). 😁

In [your comment on #827](https://github.com/microsoft/TSJS-lib-generator/pull/827#issuecomment-595426888), you mentioned that it wasn't appropriate to add `WritableStream.abort()` because Chromium has the only implementation. The same argument can be made for this Web IDL rework. What's our stance on this? Do we want TypeScript to be up-to-date with the specification, even though most browsers aren't up-to-date yet? (This is also the main reason why I haven't yet opened a pull request for this.)

Perhaps we could remove a bunch of types, properties and methods that are not yet supported in most browsers by adding them to `inputfiles/removedTypes.json`? For example, readable byte streams are currently not implemented by *any* browser (not even Chromium), so maybe we should remove all definitions related to that (e.g. `UnderlyingByteSource`, `ReadableByteStreamController`, `ReadableStreamBYOBReader`, etc.)? Then, once browsers start implementing this feature, we can bring those types back. We could maybe do the same for features that are only supported by a single browser, although that would remove a *lot* of types (such as `WritableStream` and `TransformStream`)... 😞

If we do decide to update our type definitions, then should we also update all type names to match those from the Web IDL? For example, I had added a [`PipeOptions` interface](https://github.com/microsoft/TSJS-lib-generator/blob/bf671e99615b06404db7a89fa9ae05bf14a8e47c/baselines/dom.generated.d.ts#L1028) to represent the second argument for `pipeTo()` and `pipeThrough()`, since previously it didn't have a name. After the Web IDL rework, this type now has an official name: [`StreamPipeOptions`](https://streams.spec.whatwg.org/#dictdef-streampipeoptions). Should we rename our `PipeOptions` to `StreamPipeOptions` (and force users to update their code)? I suppose that TypeScript is less concerned with backwards compatibility, and more with following the standards. And since the standard *has* changed in a (slightly) backwards incompatible way, TypeScript is also allowed to change as such?

**Comment by saschanaz** [comment]
> Perhaps we could remove a bunch of types, properties and methods that are not yet supported in most browsers by adding them to `inputfiles/removedTypes.json`?

Yes, that's what I have done. It shouldn't cause any compatibility problem as those have never really existed.

> We could maybe do the same for features that are only supported by a single browser, although that would remove a _lot_ of types (such as `WritableStream` and `TransformStream`)... 😞

> After the Web IDL rework, this type now has an official name: [`StreamPipeOptions`](https://streams.spec.whatwg.org/#dictdef-streampipeoptions). Should we rename our `PipeOptions` to `StreamPipeOptions` (and force users to update their code)?

I vote for removing and renaming but since it may cause a compat problem, @sandersn might have some idea.

**Comment by MattiasBuelens** [comment]
If we're going to remove everything that is not supported in at least two browser engines, there won't be a whole lot left. Looking at [the compatibility data from MDN](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API#Browser_compatibility) and [the test results from wpt.fyi](https://wpt.fyi/results/streams), we have:
* `ReadableStream` constructor (with `UnderlyingSource` and `ReadableStreamDefaultController`) (Chromium, Firefox, Safari)
* `ReadableStream.cancel()` (Chromium, Firefox, Safari)
* `ReadableStream.getReader()` (Chromium, Firefox, Safari)
* `ReadableStream.locked` (Chromium, Firefox, Safari)
* `ReadableStream.tee()` (Chromium, Firefox, Safari)
* `ByteLengthQueuingStrategy` (Chromium, Firefox, Safari)
* `CountQueuingStrategy` (Chromium, Firefox, Safari)

We wouldn't even need to worry about renaming `PipeOptions`, since only Chrome has support for `pipeTo()` and `WritableStream`s anyway. 😛

If we do decide to remove the Chromium-only classes/methods/properties from the DOM types, does that mean we have to bring back [@types/whatwg-streams](https://www.npmjs.com/package/@types/whatwg-streams)? 😕 We had deprecated that in favor of TypeScript's built-in definitions, see DefinitelyTyped/DefinitelyTyped#38785.

**Comment by MattiasBuelens** [comment]
Hang on, it looks like [WebKit does have a fairly complete implementation](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/Modules/streams?rev=264943)? It looks like it's been worked on recently, but I can't seem to find whether this is enabled by default or not...

Firefox also [appears to be working on `WritableStream`s](https://bugzilla.mozilla.org/show_bug.cgi?id=1582348) behind the `javascript.options.writable_streams` flag.

Maybe there's still hope? 😀

**Comment by saschanaz** [comment]
I'm okay to keep Chromium-only types in this specific case as 1) keeping them will prevent compatibility issue and 2) we expect others to eventually get them.

Maybe we can first remove types that never implemented and think about others.

**Comment by MattiasBuelens** [comment]
I've opened a draft PR: #890.

Hopefully, we can get a better idea of the impact by looking at what the changes will *actually* look like. 😁

**Comment by Banou26** [comment]
Could we re-add the types of `UnderlyingByteSource`, `ReadableByteStreamController`, `ReadableStreamBYOBReader`, ect... now that pretty much all evergreen browsers supports them? Firefox shipped them with 102 and chromium browsers have been supporting them for a while.
